### ISSUE TITLE
TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by goodforever** [cortezaproject/corteza-server-corredor#13]
yarn serve:dev
yarn run v1.9.4
$ ts-node-dev --debounce 200 --transpile-only --respawn --ignore-watch node_modules --ignore-watch usr --ignore-watch dist ./src/server.ts
[INFO] 18:32:54 ts-node-dev ver. 1.1.1 (using ts-node ver. 9.1.1, typescript ver. 3.9.7)
TypeError: Cannot read property 'replace' of undefined
    at Object.default_1 [as default] (/Users/foo/work/cortezaproject/corteza-server-corredor/src/check/exec-ctx.ts:18:6)
    at Object.default_1 [as default] (/Users/foo/work/cortezaproject/corteza-server-corredor/src/check/index.ts:5:14)
    at Object.<anonymous> (/Users/foo/work/cortezaproject/corteza-server-corredor/src/server.ts:19:9)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Module._compile (/Users/foo/work/cortezaproject/corteza-server-corredor/node_modules/ts-node-dev/node_modules/source-map-support/source-map-support.js:541:25)
    at Module.m._compile (/private/var/folders/40/3mms58b92l5cntc9vvm40llc0000gn/T/ts-node-dev-hook-3629543509226778.js:69:33)
    at Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at require.extensions..jsx.require.extensions..js (/private/var/folders/40/3mms58b92l5cntc9vvm40llc0000gn/T/ts-node-dev-hook-3629543509226778.js:114:20)
    at require.extensions.<computed> (/private/var/folders/40/3mms58b92l5cntc9vvm40llc0000gn/T/ts-node-dev-hook-3629543509226778.js:71:20)
    at Object.nodeDevHook [as .ts] (/Users/foo/work/cortezaproject/corteza-server-corredor/node_modules/ts-node-dev/lib/hook.js:63:13)
[ERROR] 18:32:57 TypeError: Cannot read property 'replace' of undefined

**Comment by darh** [comment]
Can you provide more context please? Does this happen when you use a certain script?

**Comment by tjerman** [comment]
I've opened a ticket for someone to inspect before the next release.
I would assume some parameter was not provided or there was an unstable version.
