### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by anborg** [cortezaproject/corteza-server-corredor#14]
I'm trying to compile it on windows [no docker]

How do I get past this error...

```log
c:\data\projects\projects_go\src\github.com\cortezaproject\corteza-server-corredor\node_modules\grpc\deps\grpc\src\core\ext\transport\chttp2\transport\writing.cc(542): warning C4804: '>': unsafe use of type 'bool' in operation [C:\data\projects\projects_go\src\github.com\cortezaproject\corteza-server-corredor\node_modules\grpc\build\grpc.vcxproj]
  alpn.cc
  http_client_filter.cc
  http_filters_plugin.cc
  message_compress_filter.cc
  http_server_filter.cc
  httpcli_security_connector.cc
  security_context.cc
  alts_credentials.cc
  composite_credentials.cc
  credentials.cc
  credentials_metadata.cc
  fake_credentials.cc
  credentials_generic.cc
  google_default_credentials.cc
  iam_credentials.cc
  json_token.cc
  jwt_credentials.cc
  jwt_verifier.cc
  local_credentials.cc
  oauth2_credentials.cc
  plugin_credentials.cc
  ssl_credentials.cc
  grpc_tls_credentials_options.cc
  spiffe_credentials.cc
  alts_security_connector.cc
  fake_security_connector.cc
  load_system_roots_fallback.cc
  load_system_roots_linux.cc
  local_security_connector.cc
  security_connector.cc
  ssl_security_connector.cc
  ssl_utils.cc
  ssl_utils_config.cc
  spiffe_security_connector.cc
  client_auth_filter.cc
  secure_endpoint.cc
  security_handshaker.cc
  server_auth_filter.cc
  target_authority_table.cc
  tsi_error.cc
  json_util.cc
  init_secure.cc
  aes_gcm.cc
  gsec.cc
  alts_counter.cc
  alts_crypter.cc
  alts_frame_protector.cc
  alts_record_protocol_crypter_common.cc
  alts_seal_privacy_integrity_crypter.cc
  alts_unseal_privacy_integrity_crypter.cc
  frame_handler.cc
  alts_handshaker_client.cc
  alts_shared_resource.cc
  alts_tsi_handshaker.cc
  alts_grpc_integrity_only_record_protocol.cc
  alts_grpc_privacy_integrity_record_protocol.cc
  alts_grpc_record_protocol_common.cc
  alts_iovec_record_protocol.cc
  alts_zero_copy_grpc_protector.cc
  check_gcp_environment.cc
  check_gcp_environment_linux.cc
  check_gcp_environment_no_op.cc
  check_gcp_environment_windows.cc
  grpc_alts_credentials_client_options.cc
  grpc_alts_credentials_options.cc
  grpc_alts_credentials_server_options.cc
  alts_tsi_utils.cc
  transport_security_common_api.cc
  altscontext.upb.c
  handshaker.upb.c
  transport_security_common.upb.c
  decode.c
  encode.c
  msg.c
c:\data\projects\projects_go\src\github.com\cortezaproject\corteza-server-corredor\node_modules\grpc\deps\grpc\third_party\upb\upb\table.int.h(239): warning C4334: '<<': result of 32-bit shift implicitly converted to 64 bits (was 64-bit shift intended?) [C:\data\projects\projects_go\src\github.com\cortezaproject\corteza-server-corredor\node_modules\grpc\build\grpc.vcxproj]
c:\data\projects\projects_go\src\github.com\cortezaproject\corteza-server-corredor\node_modules\grpc\deps\grpc\third_party\upb\upb\msg.c(36): warning C4146: unary minus operator applied to unsigned type, result still unsigned [C:\data\projects\projects_go\src\github.com\cortezaproject\corteza-server-corredor\node_modules\grpc\build\grpc.vcxproj]
c:\data\projects\projects_go\src\github.com\cortezaproject\corteza-server-corredor\node_modules\grpc\deps\grpc\third_party\upb\upb\msg.c(40): warning C4146: unary minus operator applied to unsigned type, result still unsigned [C:\data\projects\projects_go\src\github.com\cortezaproject\corteza-server-corredor\node_modules\grpc\build\grpc.vcxproj]
c:\data\projects\projects_go\src\github.com\cortezaproject\corteza-server-corredor\node_modules\grpc\deps\grpc\third_party\upb\upb\msg.c(46): warning C4146: unary minus operator applied to unsigned type, result still unsigned [C:\data\projects\projects_go\src\github.com\cortezaproject\corteza-server-corredor\node_modules\grpc\build\grpc.vcxproj]
  port.c
  table.c
c:\data\projects\projects_go\src\github.com\cortezaproject\corteza-server-corredor\node_modules\grpc\deps\grpc\third_party\upb\upb\table.int.h(239): warning C4334: '<<': result of 32-bit shift implicitly converted to 64 bits (was 64-bit shift intended?) [C:\data\projects\projects_go\src\github.com\cortezaproject\corteza-server-corredor\node_modules\grpc\build\grpc.vcxproj]
  upb.c
c:\data\projects\projects_go\src\github.com\cortezaproject\corteza-server-corredor\node_modules\grpc\deps\grpc\third_party\upb\upb\upb.c(192): warning C4116: unnamed type definition in parentheses [C:\data\projects\projects_go\src\github.com\cortezaproject\corteza-server-corredor\node_modules\grpc\build\grpc.vcxproj]
  transport_security.cc
  channel_create.cc
  channel_create_posix.cc
  authority.cc
  chttp2_connector.cc
  backend_metric.cc
  backup_poller.cc
  channel_connectivity.cc
  client_channel.cc
  client_channel_channelz.cc
  client_channel_factory.cc
  client_channel_plugin.cc
  connector.cc
  global_subchannel_pool.cc
  health_check_client.cc
  http_connect_handshaker.cc
  http_proxy.cc
  lb_policy.cc
  lb_policy_registry.cc
  local_subchannel_pool.cc
  parse_address.cc
  proxy_mapper.cc
  proxy_mapper_registry.cc
  resolver.cc
  resolver_registry.cc
  resolver_result_parsing.cc
  resolving_lb_policy.cc
  retry_throttle.cc
  server_address.cc
  service_config.cc
  subchannel.cc
  subchannel_pool_interface.cc
  deadline_filter.cc
  health.upb.c
  orca_load_report.upb.c
  gogo.upb.c
  validate.upb.c
  annotations.upb.c
  http.upb.c
  any.upb.c
  descriptor.upb.c
  duration.upb.c
  empty.upb.c
  struct.upb.c
  timestamp.upb.c
  wrappers.upb.c
  status.upb.c
  fake_transport_security.cc
  local_transport_security.cc
  ssl_session_boringssl.cc
  ssl_session_cache.cc
  ssl_session_openssl.cc
  ssl_transport_security.cc
  transport_security_grpc.cc
  chttp2_server.cc
  secure_channel_create.cc
  server_chttp2.cc
  server_chttp2_posix.cc
  inproc_plugin.cc
  inproc_transport.cc
  client_load_reporting_filter.cc
  grpclb.cc
  grpclb_channel_secure.cc
  grpclb_client_stats.cc
  load_balancer_api.cc
  load_balancer.upb.c
  fake_resolver.cc
  xds.cc
  xds_channel_secure.cc
  xds_client_stats.cc
  xds_load_balancer_api.cc
c:\data\projects\projects_go\src\github.com\cortezaproject\corteza-server-corredor\node_modules\grpc\deps\grpc\src\core\ext\filters\client_channel\lb_policy\xds\xds_load_balancer_api.cc(61): warning C4018: '<': signed/unsigned mismatch [C:\data\projects\projects_go\src\github.com\cortezaproject\corteza-server-corredor\node_modules\grpc\build\grpc.vcxproj]
  cert.upb.c
  cds.upb.c
  circuit_breaker.upb.c
  filter.upb.c
  outlier_detection.upb.c
  discovery.upb.c
  eds.upb.c
  endpoint.upb.c
  load_report.upb.c
  ads.upb.c
  lrs.upb.c
  address.upb.c
  base.upb.c
  config_source.upb.c
  grpc_service.upb.c
  health_check.upb.c
  http_uri.upb.c
  protocol.upb.c
  percent.upb.c
  range.upb.c
  pick_first.cc
  round_robin.cc
  dns_resolver_ares.cc
  grpc_ares_ev_driver.cc
  grpc_ares_ev_driver_libuv.cc
  grpc_ares_ev_driver_posix.cc
  grpc_ares_ev_driver_windows.cc
  grpc_ares_wrapper.cc
  grpc_ares_wrapper_fallback.cc
  grpc_ares_wrapper_libuv.cc
  grpc_ares_wrapper_posix.cc
  grpc_ares_wrapper_windows.cc
  dns_resolver_selection.cc
  dns_resolver.cc
  sockaddr_resolver.cc
  xds_resolver.cc
  grpc_context.cc
  client_idle_filter.cc
  max_age_filter.cc
  message_size_filter.cc
  client_authority_filter.cc
  workaround_cronet_compression_filter.cc
  workaround_utils.cc
  grpc_plugin_registry.cc
  win_delay_load_hook.cc
  grpc.vcxproj -> C:\data\projects\projects_go\src\github.com\cortezaproject\corteza-server-corredor\node_modules\grpc\build\Release\\libgrpc.lib
  adler32.c
  compress.c
  crc32.c
  deflate.c
  gzclose.c
  gzlib.c
  gzread.c
  gzwrite.c
  infback.c
  inffast.c
  inflate.c
  inftrees.c
  trees.c
  uncompr.c
  zutil.c
  win_delay_load_hook.cc
  z.vcxproj -> C:\data\projects\projects_go\src\github.com\cortezaproject\corteza-server-corredor\node_modules\grpc\build\Release\\libz.lib
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\apps\scoop\core\persist\nvm\nodejs\v15.3.0\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (node:events:376:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:277:12)
gyp ERR! System Windows_NT 10.0.18363
gyp ERR! command "C:\\apps\\scoop\\core\\apps\\nvm\\current\\nodejs\\nodejs\\node.exe" "C:\\apps\\scoop\\core\\apps\\nvm\\current\\nodejs\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--library=static_library" "--module=C:\\data\\projects\\projects_go\\src\\github.com\\cortezaproject\\corteza-server-corredor\\node_modules\\grpc\\src\\node\\extension_binary\\node-v88-win32-x64-unknown\\grpc_node.node" "--module_name=grpc_node" "--module_path=C:\\data\\projects\\projects_go\\src\\github.com\\cortezaproject\\corteza-server-corredor\\node_modules\\grpc\\src\\node\\extension_binary\\node-v88-win32-x64-unknown" "--napi_version=7" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v88"
gyp ERR! cwd C:\data\projects\projects_go\src\github.com\cortezaproject\corteza-server-corredor\node_modules\grpc
gyp ERR! node -v v15.3.0
gyp ERR! node-gyp -v v7.1.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd build --fallback-to-build --library=static_library --module=C:\data\projects\projects_go\src\github.com\cortezaproject\corteza-server-corredor\node_modules\grpc\src\node\extension_binary\node-v88-win32-x64-unknown\grpc_node.node --module_name=grpc_node --module_path=C:\data\projects\projects_go\src\github.com\cortezaproject\corteza-server-corredor\node_modules\grpc\src\node\extension_binary\node-v88-win32-x64-unknown --napi_version=7 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v88' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\data\projects\projects_go\src\github.com\cortezaproject\corteza-server-corredor\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:376:20)
node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1055:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:288:5)
node-pre-gyp ERR! System Windows_NT 10.0.18363
node-pre-gyp ERR! command "C:\\apps\\scoop\\core\\apps\\nvm\\current\\nodejs\\nodejs\\node.exe" "C:\\data\\projects\\projects_go\\src\\github.com\\cortezaproject\\corteza-server-corredor\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build" "--library=static_library"
node-pre-gyp ERR! cwd C:\data\projects\projects_go\src\github.com\cortezaproject\corteza-server-corredor\node_modules\grpc
node-pre-gyp ERR! node -v v15.3.0
node-pre-gyp ERR! node-pre-gyp -v v0.16.0
node-pre-gyp ERR! not ok
Failed to execute 'node-gyp.cmd build --fallback-to-build --library=static_library --module=C:\data\projects\projects_go\src\github.com\cortezaproject\corteza-server-corredor\node_modules\grpc\src\node\extension_binary\node-v88-win32-x64-unknown\grpc_node.node --module_name=grpc_node --module_path=C:\data\projects\projects_go\src\github.com\cortezaproject\corteza-server-corredor\node_modules\grpc\src\node\extension_binary\node-v88-win32-x64-unk
```

**Comment by darh** [comment]
This looks like a Node.js error.
Did you find any help online? Is this still an issue?

**Comment by tjerman** [comment]
I've opened a ticket for someone to inspect before the next release.
